# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               thathungrymind
tagline:             'my brain food'
description:         'thathungrymind | my brain food'
url:                 #http://lanyon.getpoole.com
baseurl:             #''
gems:                [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Paul Le
  url:               https://twitter.com/paululele
  email:             l.nguyen.paul@gmail.com

# Custom vars
version:             1.0.0
